services:
  - type: web
    name: batobhav
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn BatoBhav.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.8
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False